apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: slf3ow41s-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/slf3ow41s-dotnet-basic-gitops